package hibernate;
// Generated 12-mar-2019 14:12:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int idProfesor;
     private Set alumnos = new HashSet(0);
     private Set asignaturas = new HashSet(0);

    public Clase() {
    }

	
    public Clase(String nombre, int idProfesor) {
        this.nombre = nombre;
        this.idProfesor = idProfesor;
    }
    public Clase(String nombre, int idProfesor, Set alumnos, Set asignaturas) {
       this.nombre = nombre;
       this.idProfesor = idProfesor;
       this.alumnos = alumnos;
       this.asignaturas = asignaturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }




}


