package com.example.model;
// Generated 12-mar-2019 14:12:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private Clase clase;
     private String nombre;
     private String apellido;
     private Date fechaNac;
     private Float media;
     private Boolean aprobado;

    public Alumno() {
    }

	
    public Alumno(Clase clase, String nombre, String apellido, Date fechaNac) {
        this.clase = clase;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNac = fechaNac;
    }
    public Alumno(Clase clase, String nombre, String apellido, Date fechaNac, Float media, Boolean aprobado) {
       this.clase = clase;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNac = fechaNac;
       this.media = media;
       this.aprobado = aprobado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Float getMedia() {
        return this.media;
    }
    
    public void setMedia(Float media) {
        this.media = media;
    }
    public Boolean getAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(Boolean aprobado) {
        this.aprobado = aprobado;
    }




}


