package com.example.model;
// Generated 12-mar-2019 14:12:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private Date fechaNac;
     private int telefono;
     private String correo;
     private Set asignaturas = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(String nombre, String apellido, Date fechaNac, int telefono, String correo) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNac = fechaNac;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Profesor(String nombre, String apellido, Date fechaNac, int telefono, String correo, Set asignaturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNac = fechaNac;
       this.telefono = telefono;
       this.correo = correo;
       this.asignaturas = asignaturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }




}


